title: Tristan Chaang's Page
author: Tristan Chaang
email: tchaang@mit.edu
description: > # this means to ignore newlines until "twitter_username:"
  If you want to contact me, please do so via email. Thanks!

# social links
# twitter_username:
# rss: rss
github_username: Tristanchaang
# dribbble_username:
facebook_username: chaangtristan
# flickr_username:
# instagram_username: tristan_chaang
linkedin_username: tchaang
# pinterest_username:
youtube_username: "016tristan"
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - pages/index.md
  - pages/about.md
  - pages/maths.md
  - pages/handouts.md
  - pages/notes.md
  - pages/privacy.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: G-PH72KY1MTT
